############################################################
# docker-compose.yml - aplicación en node.js - Express
############################################################

# version 2
services:
    web:
      build: .
      depends_on:
        - db
      ports:
        - 5000:5000
      volumes:
        - /opt/app

    db:
      image: mongo
      expose:
        - "27017"
      volumes:
      - /home/<user>/mongodata:/data/db

